### PR TITLE
Enter two numbers to find their gcd. Eg: input: 15 10   output:5

### PR DESCRIPTION
**Pull request by pratyushranjan2**
This is a program to find the greatest common divisor of two numbers.
Eg: input: 2 5
      output: 1

### CODE REVIEW

**Comment by pratyushranjan2** [comment]
I've already given it

**Comment by moogacs** [comment]
@pratyushranjan2  it has to be as a comment in the source code itself

**Comment by pratyushranjan2** [comment]
> @pratyushranjan2 it has to be as a comment in the source code itself

**Comment by pratyushranjan2** [comment]
Done

**Pull request closed without merging**
