### PR TITLE
Create caesar.c

### PR DESCRIPTION
**Pull request by faisal-zulfiqar**
This is the implementation of caesar cipher in c language.

### CODE REVIEW

**Comment by moogacs** [comment]
@faisal-zulfiqar  thanks for your contribution, could you add a problem explanation at the beginning as comment

**Comment by faisal-zulfiqar** [comment]
@moogacs inside the code file as comment right?

**Comment by faisal-zulfiqar** [comment]
@moogacs I've added the description. Let me know if it works for you.

**Comment by moogacs** [comment]
@faisal-zulfiqar  thanks 👍  it's merged

**Pull request merged**
