### PR TITLE
Issue #19 : Add Recursive solution to find sum of digits of positive in…

### PR DESCRIPTION
**Pull request by navi532**
Problem is to find sum of digits of a positive integer using recursive method. e.g
Input= 123
Output= Sum of its digits: 6

### CODE REVIEW

**Comment by navi532** [comment]
Problem is to find sum of digits of a positive integer using recursive method. e.g
Input= 123
Output= Sum of its digits: 6

**Comment by navi532** [comment]
Is it okay, now?

**Comment by moogacs** [comment]
You need to add a descriptive discription , some thing with an example

Input/output

**Comment by navi532** [comment]
I have to mention descriptive description where? On here or on separate file ?

**Pull request merged**
